// state argument is not application state - only the 
// state generated by THIS reducer, i.e. the state 
// previous to this action.
// state = null - es6 default parameter to avoid undefined
// as initial application state    
export default function(state = null, action) {
    switch(action.type) {
        case 'BOOK_SELECTED': 
        return action.payload; 
    }

    return state; // default option returns same state
}